name: ad_sdk_example
description: Example app demonstrating the ad_sdk package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  applovin_admob_sdk: ^1.0.6
#  applovin_admob_sdk:
#    path: ../

flutter:
  uses-material-design: true
